apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-cm
  namespace: default
data:
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: example password
  WORDPRESS_DB_HOST: mysql-db.default.svc.cluster.local
  WORDPRESS_DEBUG: "true"
